theme: jekyll-theme-cayman
title: Self-supervised Learning for Cancer Pathology Foundation Models (SLC-PFM)
description: NeurIPS 2025 Competition
repository: neerajkumarvaid/ssl4pfm
baseurl: ""
url: "https://deeplearningpathology.org"
