theme: jekyll-theme-cayman
title: NeurIPS 2025 Competition
description: Self-supervised Learning for Pathology Foundation Models (SLC-PFM)
repository: neerajkumarvaid/ssl4pfm
baseurl: ""
url: "https://deeplearningpathology.org"
